### ISSUE TITLE
rlwrap ncat localhost 50505 does not work

### ISSUE THREAD

**Issue by pwhittin** [juxt/site#51]
Site Commit Hash: a696e48c36e29e0225088e0c7de0358e1fa36a35

Executing the following:
```bash
nmap -A -v -v localhost
```
on a Linux machine running site-server does find port 50505 open.

**Comment by malcolmsparks** [comment]
Thanks for spotting that. Looks like e2041c24b84df4aba27129c5ed3b9c4fde1462bf replaced 50505 with 50506. I'll fix that.
